language: php

php:
  - 7.2

install:
  # Install composer packages
  - composer install --no-interaction --ignore-platform-reqs
  # Install coveralls.phar
  - composer require --dev --no-interaction couscous/couscous

script:
  - vendor/bin/couscous travis-auto-deploy

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

notifications:
  email: false

