language: php

php:
  - 7.1

install:
  # Install composer packages
  - travis_retry composer install --no-interaction --ignore-platform-reqs
  # Install coveralls.phar
  - travis_retry composer require --dev --no-interaction couscous/couscous

script:
  - vendor/bin/couscous travis-auto-deploy

# Tell Travis CI to monitor only 'master' branch
branches:
  only: master

notifications:
  email: false

